"""Command-line interface for the scenario review engine.

Formats: table (console), json (machines), md (reports/PRs). Exit codes: 0 clean at
the chosen threshold, 1 findings found, 2 usage/parse error.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .engine import ReviewEngine
from .models import SEVERITY_RANK, Scenario, Severity
from .rules import ALL_RULES

SCAFFOLD = """\
# Generated by `scenario-review init` - edit and review!
id: my-scenario
title: My scenario title
stack: python
prompt: >
  Describe the task precisely. No vague terms like "handle errors properly".
expected_behavior: >
  What the assistant must return, with measurable acceptance criteria.
constraints: >
  Hard rules: performance envelope, forbidden dependencies, etc.
reference_solution: |
  def solve(data):
      return data
"""


def _severity_threshold(value: str) -> Severity:
    try:
        return Severity(value)
    except ValueError:
        raise argparse.ArgumentTypeError(f"unknown severity: {value}") from None


def _add_review_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("scenario", type=Path, help="path to scenario YAML")
    parser.add_argument(
        "-f", "--format",
        choices=("table", "json", "md"),
        default="table",
        help="output format (default: table)",
    )
    parser.add_argument("-o", "--output", type=Path, help="write report to file instead of stdout")
    parser.add_argument(
        "--fail-on",
        type=_severity_threshold,
        default=Severity.MEDIUM,
        help="exit 1 if any finding is at or above this severity (default: medium)",
    )


def _render_table(report) -> str:
    lines = [
        f"scenario: {report.scenario.title}",
        f"stack: {report.scenario.stack}",
        "",
    ]
    for issue in report.sorted_issues():
        tag = f"[{issue.severity.value:<5}]"
        lines.append(f"{tag} {issue.rule_id:<8} {issue.message}")
        if issue.evidence:
            lines.append(f"{'':11} evidence: {issue.evidence[:100]}")
    lines.append("")
    lines.append(f"Score: {report.overall_score:.1f} / 5")
    for dim in report.dimension_scores:
        lines.append(f"  {dim.dimension:<22} {dim.score:.1f}  {dim.rationale}")
    lines.append(report.summary)
    return "\n".join(lines)


def _render_markdown(report) -> str:
    dims = "".join(
        f"| {d.dimension} | {d.score:.1f} | {d.rationale} |\n" for d in report.dimension_scores
    )
    issues = "".join(
        f"| {i.severity.value} | {i.rule_id} | {i.category} | {i.message} | {i.evidence} | {i.suggestion} |\n"
        for i in report.sorted_issues()
    ) or "| - | - | - | No findings. | | |\n"
    return f"""# Scenario review: {report.scenario.title}

- **Scenario id:** `{report.scenario.id}`
- **Stack:** {report.scenario.stack}
- **Engine:** v{report.engine_version} · {report.rules_run} rules run

## Verdict

> {report.summary}

## Rubric

| Dimension | Score | Rationale |
| --------- | ----- | --------- |
{dims}
## Findings

| Severity | Rule | Category | Message | Evidence | Suggestion |
| -------- | ---- | -------- | ------- | -------- | ---------- |
{issues}"""


def _render_json(report) -> str:
    return json.dumps(report.to_dict(), indent=2, sort_keys=False)


RENDERERS = {"table": _render_table, "json": _render_json, "md": _render_markdown}


def _cmd_review(args) -> int:
    try:
        report = ReviewEngine().run_path(args.scenario)
    except (OSError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    text = RENDERERS[args.format](report)
    if args.output:
        args.output.write_text(text, encoding="utf-8")
        print(f"report written to {args.output}", file=sys.stderr)
    else:
        print(text)
    threshold_rank = SEVERITY_RANK[args.fail_on]
    worst_rank = min((SEVERITY_RANK[i.severity] for i in report.issues), default=99)
    return 1 if worst_rank <= threshold_rank else 0


def _cmd_rules(args) -> int:
    rules = sorted(ALL_RULES, key=lambda r: r.rule_id)
    matches = [r for r in rules if not args.category or r.category == args.category]
    header = f"{'RULE':<8} {'NAME':<30} {'CATEGORY':<16} {'DEFAULT SEVERITY':<18} DESCRIPTION"
    print(header)
    print("-" * len(header))
    for rule in matches:
        print(
            f"{rule.rule_id:<8} {rule.name:<30} {rule.category:<16} "
            f"{rule.default_severity.value:<18} {rule.description}"
        )
    print(f"\n{len(matches)} rule(s) registered (engine v{__version__})")
    return 0


def _cmd_init(args) -> int:
    target = args.path / "scenario.yaml"
    if target.exists():
        print(f"error: {target} already exists", file=sys.stderr)
        return 2
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(SCAFFOLD, encoding="utf-8")
    print(f"scaffolded {target}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="scenario-review",
        description="Systematic review of AI training & evaluation scenarios.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p_review = sub.add_parser("review", help="review a scenario YAML file")
    _add_review_args(p_review)

    p_rules = sub.add_parser("rules", help="list the rule catalog")
    p_rules.add_argument("--category", choices=("clarity", "correctness", "edge_case_coverage", "safety", "testability"))

    p_init = sub.add_parser("init", help="scaffold a starter scenario")
    p_init.add_argument("path", nargs="?", type=Path, default=Path("."))
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.command == "review":
        return _cmd_review(args)
    if args.command == "rules":
        return _cmd_rules(args)
    if args.command == "init":
        return _cmd_init(args)
    print("error: unknown command", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())